name: Deploy to GitHub Pages

on:
  # Se déclenche quand tu push sur la branche main
  push:
    branches: ["main"]

  # Permet de lancer manuellement depuis l'onglet Actions
  workflow_dispatch:

# Droits nécessaires pour le déploiement
permissions:
  contents: read
  pages: write
  id-token: write

# Une seule publication à la fois
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Étape de construction (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Construction du site (Build)
        run: npm run build

      - name: Préparer l'artefact pour GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Le dossier créé par Vite s'appelle 'dist'

  # Étape de déploiement (Deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4